blank_issues_enabled: false
contact_links:
  - name: â“ Ask a question or start a discussion
    url: https://github.com/ArchiveBox/ArchiveBox/discussions
    about: "Ask a question, get support, or start a design discussion (to report a problem please use 'ğŸ Bug report' instead)"
  - name: ğŸ’¬ Chat with the dev team & community on Zulip
    url: https://zulip.archivebox.io
    about: "Join us on our Zulip forum to chat with the developers and other users (it's similar to Discord but self-hosted)."
  - name: ğŸ’â€â™‚ï¸ Hire us for professional support with fast response times
    url: https://docs.monadical.com/s/archivebox-consulting-services
    about: "We provide hosting, develoment, and support, including on-prem/cloud w/ SSO & storage, CAPTCHA-solving, proxies, etc."
