name: Build Debian package

on:
  workflow_dispatch:
  push:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64

      - name: Build Debian/Apt package
        run: |
          sudo apt install -y python3 python3-dev python3-pip python3-venv python3-all dh-python debhelper devscripts dput software-properties-common python3-setuptools python3-wheel python3-stdeb
          pip3 install --upgrade pip setuptools wheel stdeb
          ./bin/build_deb.sh

      - name: Install archivebox from deb
        run: |
          apt install deb_dist/archivebox*.deb

      - name: Add some links to test
        run: |
          mkdir data && cd data
          archivebox init
          archivebox add 'https://example.com'
          archivebox version
          archivebox status

      # TODO: push debian package to launchpad PPA
      # - name: Push to launchpad
      #   run: |
      #     dput archivebox "deb_dist/archivebox_${VERSION}-${DEBIAN_VERSION}_source.changes"
